vk:
  orientdb:
    url: ${ORIENTDB_URL}
    dbName: ${ORIENTDB_DBNAME}
    username: ${ORIENTDB_USERNAME}
    password: ${ORIENTDB_PASSWORD}
  redis:
    hostname: ${REDIS_HOSTNAME}
    port: ${REDIS_PORT}
    collection-name: ids
    batch-insert-size: 5000