version: "3.0"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark-streaming:
    image: spark-streaming/spark-streaming:latest
    depends_on:
      - generator
      - kafka
    ports:
      - "4040:4040"
    environment:
      SPARK_MASTER: local[*]
      SPARK_UI_PORT: 4040
      BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      FRIENDS_SOURCE: friends
      FRIENDS_SINK: vk_data
      PROFILES_SOURCE: profiles
      PROFILES_SINK: vk_data

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  kafka-orientdb-sink1:
    image: fluffytiger/kafka-orientdb-sink:1.0-SNAPSHOT
    depends_on:
      - kafka
      - odb1
      - odb2
      - redis
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      MAX_POLL_RECORDS: 5000
      ORIENTDB_URL: remote:odb1:2424
      ORIENTDB_DBNAME: vk_data
      ORIENTDB_USERNAME: root
      ORIENTDB_PASSWORD: root
      ORIENTDB_SUFFIX: _1
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379

  kafka-orientdb-sink2:
    image: fluffytiger/kafka-orientdb-sink:1.0-SNAPSHOT
    depends_on:
      - kafka
      - odb1
      - odb2
      - redis
    ports:
      - "8081:8080"
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      MAX_POLL_RECORDS: 5000
      ORIENTDB_URL: remote:odb2:2424
      ORIENTDB_DBNAME: vk_data
      ORIENTDB_USERNAME: root
      ORIENTDB_PASSWORD: root
      ORIENTDB_SUFFIX: _2
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379

  odb-init:
    image: orientdb:latest
    volumes:
      - ./orientdb-init:/var/scripts
    depends_on:
      - odb1
      - odb2
    environment:
      ORIENTDB_ROOT_PASSWORD: root
    restart: "no"
    command: sh -c "sleep 60 && console.sh /var/scripts/setup.txt"

  odb1:
    image: orientdb:latest
    command: dserver.sh
    volumes:
      - ./orientdb/odb1/config:/orientdb/config
      - ./orientdb/odb1/databases:/orientdb/databases
    environment:
      ORIENTDB_ROOT_PASSWORD: root
      ORIENTDB_NODE_NAME: odb1
    ports:
      - "2481:2480"

  odb2:
    image: orientdb:latest
    command: dserver.sh
    volumes:
      - ./orientdb/odb2/config:/orientdb/config
      - ./orientdb/odb2/databases:/orientdb/databases
    environment:
      ORIENTDB_ROOT_PASSWORD: root
      ORIENTDB_NODE_NAME: odb2
    ports:
      - "2482:2480"