version: "3.0"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: bitnami/redis:latest
    depends_on:
      - odb3
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  kafka-orientdb-sink:
    image: fluffytiger/kafka-orientdb-sink:1.0-SNAPSHOT
    depends_on:
      - kafka
      - odb1
      - odb2
      - odb3
      - redis
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      ORIENTDB_URL: remote:odb1:2424;odb2:2424;odb3:2424/vk_data
      ORIENTDB_DBNAME: vk_data
      ORIENTDB_USERNAME: root
      ORIENTDB_PASSWORD: root
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379

  odb1:
    image: orientdb:latest
    command: dserver.sh
    volumes:
      - ./var1/odb1/config:/orientdb/config
      - ./var1/odb1/databases:/orientdb/databases
    environment:
      ORIENTDB_ROOT_PASSWORD: root
      ORIENTDB_NODE_NAME: odb1
    ports:
      - 2480:2480

  odb2:
    image: orientdb:latest
    command: dserver.sh
    volumes:
      - ./var1/odb2/config:/orientdb/config
      - ./var1/odb2/databases:/orientdb/databases
    environment:
      ORIENTDB_ROOT_PASSWORD: root
      ORIENTDB_NODE_NAME: odb2
    depends_on:
      - odb1
    ports:
      - 2481:2480

  odb3:
    image: orientdb:latest
    command: dserver.sh
    volumes:
      - ./var1/odb3/config:/orientdb/config
      - ./var1/odb3/databases:/orientdb/databases
    environment:
      ORIENTDB_ROOT_PASSWORD: root
      ORIENTDB_NODE_NAME: odb3
    depends_on:
      - odb2
    ports:
      - 2482:2480
